spark.catalog.setCurrentCatalog("purgo_databricks")

# Test Data Generation for purgo_playground.dosage_response_analysis
# PySpark code for comprehensive test data covering happy path, edge, error, and special cases

# from pyspark.sql import SparkSession  # SparkSession is already available in Databricks
from pyspark.sql.types import (  
    StructType, StructField, StringType, DoubleType, LongType, IntegerType
)
from pyspark.sql import Row  
from pyspark.sql.functions import lit  

# Define schema for purgo_playground.dosage_response_analysis
dosage_response_schema = StructType([
    StructField("study_id", StringType(), True),
    StructField("compound_id", StringType(), True),
    StructField("dose_mg", DoubleType(), True),
    StructField("response_pct", LongType(), True),
    StructField("subject_id", StringType(), True),
    StructField("time_hr", LongType(), True),
    StructField("cell_line", StringType(), True),
    StructField("drug_name", StringType(), True),
    StructField("gene_mutation", StringType(), True),
    StructField("mutation_type", StringType(), True),
    StructField("target_protein", StringType(), True),
    StructField("receptor_type", StringType(), True),
    StructField("toxicity_level", StringType(), True),
    StructField("efficacy_score", LongType(), True),
    StructField("ic50", DoubleType(), True),
    StructField("auc", LongType(), True),
    StructField("therapeutic_area", StringType(), True),
    StructField("organism", StringType(), True),
    StructField("tissue_type", StringType(), True),
    StructField("test_batch", StringType(), True),
    StructField("test_lab", StringType(), True),
    StructField("temperature_c", LongType(), True),
    StructField("ph_level", DoubleType(), True),
    StructField("solvent", StringType(), True),
    StructField("plate_id", StringType(), True),
    StructField("replicate_count", LongType(), True),
    StructField("analyst", StringType(), True),
    StructField("approved_flag", StringType(), True),
    StructField("date_tested", StringType(), True)
])

# Test data rows
test_data = [
    # Happy Path: Complete data for CMPD001
    Row(study_id="STUDY001", compound_id="CMPD001", dose_mg=10.0, response_pct=80, subject_id="SUBJ001", time_hr=24, cell_line="A549", drug_name="DrugA", gene_mutation="MUT1", mutation_type="TypeA", target_protein="TP53", receptor_type="R1", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Lung", test_batch="B1", test_lab="LabA", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P1", replicate_count=3, analyst="Analyst1", approved_flag="Y", date_tested="2024-03-21T00:00:00.000+0000"),
    Row(study_id="STUDY001", compound_id="CMPD001", dose_mg=20.0, response_pct=85, subject_id="SUBJ002", time_hr=24, cell_line="A549", drug_name="DrugA", gene_mutation="MUT1", mutation_type="TypeA", target_protein="TP53", receptor_type="R1", toxicity_level="Low", efficacy_score=92, ic50=1.7, auc=125, therapeutic_area="Oncology", organism="Human", tissue_type="Lung", test_batch="B1", test_lab="LabA", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P1", replicate_count=3, analyst="Analyst1", approved_flag="Y", date_tested="2024-03-22T00:00:00.000+0000"),
    Row(study_id="STUDY001", compound_id="CMPD001", dose_mg=15.0, response_pct=82, subject_id="SUBJ003", time_hr=24, cell_line="A549", drug_name="DrugA", gene_mutation="MUT1", mutation_type="TypeA", target_protein="TP53", receptor_type="R1", toxicity_level="Low", efficacy_score=91, ic50=1.6, auc=122, therapeutic_area="Oncology", organism="Human", tissue_type="Lung", test_batch="B1", test_lab="LabA", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P1", replicate_count=3, analyst="Analyst1", approved_flag="Y", date_tested="2024-03-23T00:00:00.000+0000"),
    # Potency Level: High (avg_ic50 < 2.0)
    Row(study_id="STUDY002", compound_id="CMPD002", dose_mg=12.0, response_pct=78, subject_id="SUBJ004", time_hr=24, cell_line="MCF7", drug_name="DrugB", gene_mutation="MUT2", mutation_type="TypeB", target_protein="EGFR", receptor_type="R2", toxicity_level="Medium", efficacy_score=88, ic50=1.0, auc=110, therapeutic_area="Oncology", organism="Human", tissue_type="Breast", test_batch="B2", test_lab="LabB", temperature_c=37, ph_level=7.2, solvent="EtOH", plate_id="P2", replicate_count=2, analyst="Analyst2", approved_flag="Y", date_tested="2024-03-24T00:00:00.000+0000"),
    Row(study_id="STUDY002", compound_id="CMPD002", dose_mg=14.0, response_pct=79, subject_id="SUBJ005", time_hr=24, cell_line="MCF7", drug_name="DrugB", gene_mutation="MUT2", mutation_type="TypeB", target_protein="EGFR", receptor_type="R2", toxicity_level="Medium", efficacy_score=89, ic50=1.5, auc=112, therapeutic_area="Oncology", organism="Human", tissue_type="Breast", test_batch="B2", test_lab="LabB", temperature_c=37, ph_level=7.2, solvent="EtOH", plate_id="P2", replicate_count=2, analyst="Analyst2", approved_flag="Y", date_tested="2024-03-25T00:00:00.000+0000"),
    Row(study_id="STUDY002", compound_id="CMPD002", dose_mg=13.0, response_pct=80, subject_id="SUBJ006", time_hr=24, cell_line="MCF7", drug_name="DrugB", gene_mutation="MUT2", mutation_type="TypeB", target_protein="EGFR", receptor_type="R2", toxicity_level="Medium", efficacy_score=90, ic50=1.8, auc=115, therapeutic_area="Oncology", organism="Human", tissue_type="Breast", test_batch="B2", test_lab="LabB", temperature_c=37, ph_level=7.2, solvent="EtOH", plate_id="P2", replicate_count=2, analyst="Analyst2", approved_flag="Y", date_tested="2024-03-26T00:00:00.000+0000"),
    # Potency Level: Moderate (2.0 <= avg_ic50 <= 4.0)
    Row(study_id="STUDY003", compound_id="CMPD003", dose_mg=10.0, response_pct=70, subject_id="SUBJ007", time_hr=24, cell_line="HCT116", drug_name="DrugC", gene_mutation="MUT3", mutation_type="TypeC", target_protein="KRAS", receptor_type="R3", toxicity_level="High", efficacy_score=80, ic50=2.0, auc=100, therapeutic_area="Oncology", organism="Human", tissue_type="Colon", test_batch="B3", test_lab="LabC", temperature_c=37, ph_level=7.0, solvent="Water", plate_id="P3", replicate_count=1, analyst="Analyst3", approved_flag="N", date_tested="2024-03-27T00:00:00.000+0000"),
    Row(study_id="STUDY003", compound_id="CMPD003", dose_mg=20.0, response_pct=75, subject_id="SUBJ008", time_hr=24, cell_line="HCT116", drug_name="DrugC", gene_mutation="MUT3", mutation_type="TypeC", target_protein="KRAS", receptor_type="R3", toxicity_level="High", efficacy_score=82, ic50=2.5, auc=105, therapeutic_area="Oncology", organism="Human", tissue_type="Colon", test_batch="B3", test_lab="LabC", temperature_c=37, ph_level=7.0, solvent="Water", plate_id="P3", replicate_count=1, analyst="Analyst3", approved_flag="N", date_tested="2024-03-28T00:00:00.000+0000"),
    Row(study_id="STUDY003", compound_id="CMPD003", dose_mg=15.0, response_pct=72, subject_id="SUBJ009", time_hr=24, cell_line="HCT116", drug_name="DrugC", gene_mutation="MUT3", mutation_type="TypeC", target_protein="KRAS", receptor_type="R3", toxicity_level="High", efficacy_score=81, ic50=3.0, auc=102, therapeutic_area="Oncology", organism="Human", tissue_type="Colon", test_batch="B3", test_lab="LabC", temperature_c=37, ph_level=7.0, solvent="Water", plate_id="P3", replicate_count=1, analyst="Analyst3", approved_flag="N", date_tested="2024-03-29T00:00:00.000+0000"),
    Row(study_id="STUDY003", compound_id="CMPD003", dose_mg=18.0, response_pct=74, subject_id="SUBJ010", time_hr=24, cell_line="HCT116", drug_name="DrugC", gene_mutation="MUT3", mutation_type="TypeC", target_protein="KRAS", receptor_type="R3", toxicity_level="High", efficacy_score=83, ic50=4.0, auc=108, therapeutic_area="Oncology", organism="Human", tissue_type="Colon", test_batch="B3", test_lab="LabC", temperature_c=37, ph_level=7.0, solvent="Water", plate_id="P3", replicate_count=1, analyst="Analyst3", approved_flag="N", date_tested="2024-03-30T00:00:00.000+0000"),
    # Potency Level: Low (avg_ic50 > 4.0)
    Row(study_id="STUDY004", compound_id="CMPD004", dose_mg=25.0, response_pct=60, subject_id="SUBJ011", time_hr=24, cell_line="PC3", drug_name="DrugD", gene_mutation="MUT4", mutation_type="TypeD", target_protein="ALK", receptor_type="R4", toxicity_level="Medium", efficacy_score=70, ic50=4.1, auc=90, therapeutic_area="Oncology", organism="Human", tissue_type="Prostate", test_batch="B4", test_lab="LabD", temperature_c=37, ph_level=7.3, solvent="DMSO", plate_id="P4", replicate_count=2, analyst="Analyst4", approved_flag="Y", date_tested="2024-03-31T00:00:00.000+0000"),
    Row(study_id="STUDY004", compound_id="CMPD004", dose_mg=30.0, response_pct=62, subject_id="SUBJ012", time_hr=24, cell_line="PC3", drug_name="DrugD", gene_mutation="MUT4", mutation_type="TypeD", target_protein="ALK", receptor_type="R4", toxicity_level="Medium", efficacy_score=72, ic50=5.0, auc=95, therapeutic_area="Oncology", organism="Human", tissue_type="Prostate", test_batch="B4", test_lab="LabD", temperature_c=37, ph_level=7.3, solvent="DMSO", plate_id="P4", replicate_count=2, analyst="Analyst4", approved_flag="Y", date_tested="2024-04-01T00:00:00.000+0000"),
    Row(study_id="STUDY004", compound_id="CMPD004", dose_mg=28.0, response_pct=61, subject_id="SUBJ013", time_hr=24, cell_line="PC3", drug_name="DrugD", gene_mutation="MUT4", mutation_type="TypeD", target_protein="ALK", receptor_type="R4", toxicity_level="Medium", efficacy_score=71, ic50=6.0, auc=92, therapeutic_area="Oncology", organism="Human", tissue_type="Prostate", test_batch="B4", test_lab="LabD", temperature_c=37, ph_level=7.3, solvent="DMSO", plate_id="P4", replicate_count=2, analyst="Analyst4", approved_flag="Y", date_tested="2024-04-02T00:00:00.000+0000"),
    # Null Handling: Some nulls for CMPD005
    Row(study_id="STUDY005", compound_id="CMPD005", dose_mg=10.0, response_pct=80, subject_id="SUBJ014", time_hr=24, cell_line="U2OS", drug_name="DrugE", gene_mutation="MUT5", mutation_type="TypeE", target_protein="BRAF", receptor_type="R5", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Bone", test_batch="B5", test_lab="LabE", temperature_c=37, ph_level=7.1, solvent="DMSO", plate_id="P5", replicate_count=1, analyst="Analyst5", approved_flag="Y", date_tested="2024-04-03T00:00:00.000+0000"),
    Row(study_id="STUDY005", compound_id="CMPD005", dose_mg=None, response_pct=85, subject_id="SUBJ015", time_hr=24, cell_line="U2OS", drug_name="DrugE", gene_mutation="MUT5", mutation_type="TypeE", target_protein="BRAF", receptor_type="R5", toxicity_level="Low", efficacy_score=None, ic50=1.7, auc=125, therapeutic_area="Oncology", organism="Human", tissue_type="Bone", test_batch="B5", test_lab="LabE", temperature_c=37, ph_level=7.1, solvent="DMSO", plate_id="P5", replicate_count=1, analyst="Analyst5", approved_flag="Y", date_tested="2024-04-04T00:00:00.000+0000"),
    Row(study_id="STUDY005", compound_id="CMPD005", dose_mg=15.0, response_pct=None, subject_id="SUBJ016", time_hr=24, cell_line="U2OS", drug_name="DrugE", gene_mutation="MUT5", mutation_type="TypeE", target_protein="BRAF", receptor_type="R5", toxicity_level="Low", efficacy_score=91, ic50=None, auc=None, therapeutic_area="Oncology", organism="Human", tissue_type="Bone", test_batch="B5", test_lab="LabE", temperature_c=37, ph_level=7.1, solvent="DMSO", plate_id="P5", replicate_count=1, analyst="Analyst5", approved_flag="Y", date_tested="2024-04-05T00:00:00.000+0000"),
    # All Nulls for CMPD006
    Row(study_id="STUDY006", compound_id="CMPD006", dose_mg=None, response_pct=None, subject_id="SUBJ017", time_hr=24, cell_line="HEK293", drug_name="DrugF", gene_mutation="MUT6", mutation_type="TypeF", target_protein="CDK2", receptor_type="R6", toxicity_level="High", efficacy_score=None, ic50=None, auc=None, therapeutic_area="Oncology", organism="Human", tissue_type="Kidney", test_batch="B6", test_lab="LabF", temperature_c=37, ph_level=7.5, solvent="EtOH", plate_id="P6", replicate_count=1, analyst="Analyst6", approved_flag="N", date_tested="2024-04-06T00:00:00.000+0000"),
    Row(study_id="STUDY006", compound_id="CMPD006", dose_mg=None, response_pct=None, subject_id="SUBJ018", time_hr=24, cell_line="HEK293", drug_name="DrugF", gene_mutation="MUT6", mutation_type="TypeF", target_protein="CDK2", receptor_type="R6", toxicity_level="High", efficacy_score=None, ic50=None, auc=None, therapeutic_area="Oncology", organism="Human", tissue_type="Kidney", test_batch="B6", test_lab="LabF", temperature_c=37, ph_level=7.5, solvent="EtOH", plate_id="P6", replicate_count=1, analyst="Analyst6", approved_flag="N", date_tested="2024-04-07T00:00:00.000+0000"),
    # Potency Level Threshold Edge Cases
    Row(study_id="STUDY007", compound_id="CMPD009", dose_mg=10.0, response_pct=80, subject_id="SUBJ019", time_hr=24, cell_line="A375", drug_name="DrugG", gene_mutation="MUT7", mutation_type="TypeG", target_protein="PIK3CA", receptor_type="R7", toxicity_level="Low", efficacy_score=85, ic50=2.0, auc=130, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B7", test_lab="LabG", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P7", replicate_count=1, analyst="Analyst7", approved_flag="Y", date_tested="2024-04-08T00:00:00.000+0000"),
    Row(study_id="STUDY008", compound_id="CMPD010", dose_mg=10.0, response_pct=80, subject_id="SUBJ020", time_hr=24, cell_line="A375", drug_name="DrugH", gene_mutation="MUT8", mutation_type="TypeH", target_protein="PIK3CA", receptor_type="R8", toxicity_level="Low", efficacy_score=85, ic50=4.0, auc=130, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B8", test_lab="LabH", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P8", replicate_count=1, analyst="Analyst8", approved_flag="Y", date_tested="2024-04-09T00:00:00.000+0000"),
    Row(study_id="STUDY009", compound_id="CMPD011", dose_mg=10.0, response_pct=80, subject_id="SUBJ021", time_hr=24, cell_line="A375", drug_name="DrugI", gene_mutation="MUT9", mutation_type="TypeI", target_protein="PIK3CA", receptor_type="R9", toxicity_level="Low", efficacy_score=85, ic50=2.01, auc=130, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B9", test_lab="LabI", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P9", replicate_count=1, analyst="Analyst9", approved_flag="Y", date_tested="2024-04-10T00:00:00.000+0000"),
    Row(study_id="STUDY010", compound_id="CMPD012", dose_mg=10.0, response_pct=80, subject_id="SUBJ022", time_hr=24, cell_line="A375", drug_name="DrugJ", gene_mutation="MUT10", mutation_type="TypeJ", target_protein="PIK3CA", receptor_type="R10", toxicity_level="Low", efficacy_score=85, ic50=4.01, auc=130, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B10", test_lab="LabJ", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P10", replicate_count=1, analyst="Analyst10", approved_flag="Y", date_tested="2024-04-11T00:00:00.000+0000"),
    Row(study_id="STUDY011", compound_id="CMPD013", dose_mg=10.0, response_pct=80, subject_id="SUBJ023", time_hr=24, cell_line="A375", drug_name="DrugK", gene_mutation="MUT11", mutation_type="TypeK", target_protein="PIK3CA", receptor_type="R11", toxicity_level="Low", efficacy_score=85, ic50=1.99, auc=130, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B11", test_lab="LabK", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P11", replicate_count=1, analyst="Analyst11", approved_flag="Y", date_tested="2024-04-12T00:00:00.000+0000"),
    # Filtering by approved_flag (mixed Y/N)
    Row(study_id="STUDY012", compound_id="CMPD014", dose_mg=10.0, response_pct=80, subject_id="SUBJ024", time_hr=24, cell_line="A375", drug_name="DrugL", gene_mutation="MUT12", mutation_type="TypeL", target_protein="PIK3CA", receptor_type="R12", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B12", test_lab="LabL", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P12", replicate_count=1, analyst="Analyst12", approved_flag="Y", date_tested="2024-04-13T00:00:00.000+0000"),
    Row(study_id="STUDY012", compound_id="CMPD014", dose_mg=20.0, response_pct=85, subject_id="SUBJ025", time_hr=24, cell_line="A375", drug_name="DrugL", gene_mutation="MUT12", mutation_type="TypeL", target_protein="PIK3CA", receptor_type="R12", toxicity_level="Low", efficacy_score=92, ic50=1.7, auc=125, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B12", test_lab="LabL", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P12", replicate_count=1, analyst="Analyst12", approved_flag="N", date_tested="2024-04-14T00:00:00.000+0000"),
    Row(study_id="STUDY012", compound_id="CMPD014", dose_mg=15.0, response_pct=82, subject_id="SUBJ026", time_hr=24, cell_line="A375", drug_name="DrugL", gene_mutation="MUT12", mutation_type="TypeL", target_protein="PIK3CA", receptor_type="R12", toxicity_level="Low", efficacy_score=91, ic50=1.6, auc=122, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B12", test_lab="LabL", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P12", replicate_count=1, analyst="Analyst12", approved_flag="Y", date_tested="2024-04-15T00:00:00.000+0000"),
    # Special Characters and Multibyte Characters
    Row(study_id="STUDY013", compound_id="CMPD031", dose_mg=10.0, response_pct=80, subject_id="SUBJ027", time_hr=24, cell_line="A375", drug_name="DrügΩ", gene_mutation="MÜT13", mutation_type="TypeM", target_protein="PIK3CA", receptor_type="R13", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B13", test_lab="LabM", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P13", replicate_count=1, analyst="AnalystΩ", approved_flag="Y", date_tested="2024-04-16T00:00:00.000+0000"),
    # Mixed-case approved_flag
    Row(study_id="STUDY014", compound_id="CMPD023", dose_mg=10.0, response_pct=80, subject_id="SUBJ028", time_hr=24, cell_line="A375", drug_name="DrugN", gene_mutation="MUT14", mutation_type="TypeN", target_protein="PIK3CA", receptor_type="R14", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B14", test_lab="LabN", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P14", replicate_count=1, analyst="Analyst13", approved_flag="Y", date_tested="2024-04-17T00:00:00.000+0000"),
    Row(study_id="STUDY014", compound_id="CMPD023", dose_mg=10.0, response_pct=80, subject_id="SUBJ029", time_hr=24, cell_line="A375", drug_name="DrugN", gene_mutation="MUT14", mutation_type="TypeN", target_protein="PIK3CA", receptor_type="R14", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B14", test_lab="LabN", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P14", replicate_count=1, analyst="Analyst13", approved_flag="y", date_tested="2024-04-18T00:00:00.000+0000"),
    Row(study_id="STUDY014", compound_id="CMPD023", dose_mg=10.0, response_pct=80, subject_id="SUBJ030", time_hr=24, cell_line="A375", drug_name="DrugN", gene_mutation="MUT14", mutation_type="TypeN", target_protein="PIK3CA", receptor_type="R14", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B14", test_lab="LabN", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P14", replicate_count=1, analyst="Analyst13", approved_flag="N", date_tested="2024-04-19T00:00:00.000+0000"),
    Row(study_id="STUDY014", compound_id="CMPD023", dose_mg=10.0, response_pct=80, subject_id="SUBJ031", time_hr=24, cell_line="A375", drug_name="DrugN", gene_mutation="MUT14", mutation_type="TypeN", target_protein="PIK3CA", receptor_type="R14", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B14", test_lab="LabN", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P14", replicate_count=1, analyst="Analyst13", approved_flag="n", date_tested="2024-04-20T00:00:00.000+0000"),
    # Future date_tested
    Row(study_id="STUDY015", compound_id="CMPD024", dose_mg=10.0, response_pct=80, subject_id="SUBJ032", time_hr=24, cell_line="A375", drug_name="DrugO", gene_mutation="MUT15", mutation_type="TypeO", target_protein="PIK3CA", receptor_type="R15", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B15", test_lab="LabO", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P15", replicate_count=1, analyst="Analyst14", approved_flag="Y", date_tested="2099-01-01T00:00:00.000+0000"),
    # Non-unique compound_id (case-sensitive)
    Row(study_id="STUDY016", compound_id="CMPD025", dose_mg=10.0, response_pct=80, subject_id="SUBJ033", time_hr=24, cell_line="A375", drug_name="DrugP", gene_mutation="MUT16", mutation_type="TypeP", target_protein="PIK3CA", receptor_type="R16", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B16", test_lab="LabP", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P16", replicate_count=1, analyst="Analyst15", approved_flag="Y", date_tested="2024-04-21T00:00:00.000+0000"),
    Row(study_id="STUDY016", compound_id="cmpd025", dose_mg=10.0, response_pct=80, subject_id="SUBJ034", time_hr=24, cell_line="A375", drug_name="DrugP", gene_mutation="MUT16", mutation_type="TypeP", target_protein="PIK3CA", receptor_type="R16", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B16", test_lab="LabP", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P16", replicate_count=1, analyst="Analyst15", approved_flag="Y", date_tested="2024-04-22T00:00:00.000+0000"),
    # Null compound_id (should be excluded)
    Row(study_id="STUDY017", compound_id=None, dose_mg=10.0, response_pct=80, subject_id="SUBJ035", time_hr=24, cell_line="A375", drug_name="DrugQ", gene_mutation="MUT17", mutation_type="TypeQ", target_protein="PIK3CA", receptor_type="R17", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B17", test_lab="LabQ", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P17", replicate_count=1, analyst="Analyst16", approved_flag="Y", date_tested="2024-04-23T00:00:00.000+0000"),
    # Negative and zero values
    Row(study_id="STUDY018", compound_id="CMPD017", dose_mg=0.0, response_pct=80, subject_id="SUBJ036", time_hr=24, cell_line="A375", drug_name="DrugR", gene_mutation="MUT18", mutation_type="TypeR", target_protein="PIK3CA", receptor_type="R18", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B18", test_lab="LabR", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P18", replicate_count=1, analyst="Analyst17", approved_flag="Y", date_tested="2024-04-24T00:00:00.000+0000"),
    Row(study_id="STUDY018", compound_id="CMPD017", dose_mg=10.0, response_pct=80, subject_id="SUBJ037", time_hr=24, cell_line="A375", drug_name="DrugR", gene_mutation="MUT18", mutation_type="TypeR", target_protein="PIK3CA", receptor_type="R18", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B18", test_lab="LabR", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P18", replicate_count=1, analyst="Analyst17", approved_flag="Y", date_tested="2024-04-25T00:00:00.000+0000"),
    Row(study_id="STUDY019", compound_id="CMPD018", dose_mg=-5.0, response_pct=80, subject_id="SUBJ038", time_hr=24, cell_line="A375", drug_name="DrugS", gene_mutation="MUT19", mutation_type="TypeS", target_protein="PIK3CA", receptor_type="R19", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B19", test_lab="LabS", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P19", replicate_count=1, analyst="Analyst18", approved_flag="Y", date_tested="2024-04-26T00:00:00.000+0000"),
    Row(study_id="STUDY019", compound_id="CMPD018", dose_mg=15.0, response_pct=80, subject_id="SUBJ039", time_hr=24, cell_line="A375", drug_name="DrugS", gene_mutation="MUT19", mutation_type="TypeS", target_protein="PIK3CA", receptor_type="R19", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B19", test_lab="LabS", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P19", replicate_count=1, analyst="Analyst18", approved_flag="Y", date_tested="2024-04-27T00:00:00.000+0000"),
    Row(study_id="STUDY020", compound_id="CMPD019", dose_mg=10.0, response_pct=80, subject_id="SUBJ040", time_hr=24, cell_line="A375", drug_name="DrugT", gene_mutation="MUT20", mutation_type="TypeT", target_protein="PIK3CA", receptor_type="R20", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B20", test_lab="LabT", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P20", replicate_count=1, analyst="Analyst19", approved_flag="Y", date_tested="2024-04-28T00:00:00.000+0000"),
    Row(study_id="STUDY020", compound_id="CMPD019", dose_mg=20.0, response_pct=80, subject_id="SUBJ041", time_hr=24, cell_line="A375", drug_name="DrugT", gene_mutation="MUT20", mutation_type="TypeT", target_protein="PIK3CA", receptor_type="R20", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B20", test_lab="LabT", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P20", replicate_count=1, analyst="Analyst19", approved_flag="Y", date_tested="2024-04-29T00:00:00.000+0000"),
    # Negative efficacy_score, response_pct, ic50, auc
    Row(study_id="STUDY021", compound_id="CMPD027", dose_mg=10.0, response_pct=80, subject_id="SUBJ042", time_hr=24, cell_line="A375", drug_name="DrugU", gene_mutation="MUT21", mutation_type="TypeU", target_protein="PIK3CA", receptor_type="R21", toxicity_level="Low", efficacy_score=-10, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B21", test_lab="LabU", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P21", replicate_count=1, analyst="Analyst20", approved_flag="Y", date_tested="2024-04-30T00:00:00.000+0000"),
    Row(study_id="STUDY022", compound_id="CMPD028", dose_mg=10.0, response_pct=-20, subject_id="SUBJ043", time_hr=24, cell_line="A375", drug_name="DrugV", gene_mutation="MUT22", mutation_type="TypeV", target_protein="PIK3CA", receptor_type="R22", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B22", test_lab="LabV", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P22", replicate_count=1, analyst="Analyst21", approved_flag="Y", date_tested="2024-05-01T00:00:00.000+0000"),
    Row(study_id="STUDY023", compound_id="CMPD029", dose_mg=10.0, response_pct=80, subject_id="SUBJ044", time_hr=24, cell_line="A375", drug_name="DrugW", gene_mutation="MUT23", mutation_type="TypeW", target_protein="PIK3CA", receptor_type="R23", toxicity_level="Low", efficacy_score=90, ic50=-1.0, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B23", test_lab="LabW", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P23", replicate_count=1, analyst="Analyst22", approved_flag="Y", date_tested="2024-05-02T00:00:00.000+0000"),
    Row(study_id="STUDY024", compound_id="CMPD030", dose_mg=10.0, response_pct=80, subject_id="SUBJ045", time_hr=24, cell_line="A375", drug_name="DrugX", gene_mutation="MUT24", mutation_type="TypeX", target_protein="PIK3CA", receptor_type="R24", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=-100, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B24", test_lab="LabX", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P24", replicate_count=1, analyst="Analyst23", approved_flag="Y", date_tested="2024-05-03T00:00:00.000+0000"),
    # Duplicate records for CMPD021
    Row(study_id="STUDY025", compound_id="CMPD021", dose_mg=10.0, response_pct=80, subject_id="SUBJ046", time_hr=24, cell_line="A375", drug_name="DrugY", gene_mutation="MUT25", mutation_type="TypeY", target_protein="PIK3CA", receptor_type="R25", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B25", test_lab="LabY", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P25", replicate_count=1, analyst="Analyst24", approved_flag="Y", date_tested="2024-05-04T00:00:00.000+0000"),
    Row(study_id="STUDY025", compound_id="CMPD021", dose_mg=10.0, response_pct=80, subject_id="SUBJ046", time_hr=24, cell_line="A375", drug_name="DrugY", gene_mutation="MUT25", mutation_type="TypeY", target_protein="PIK3CA", receptor_type="R25", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B25", test_lab="LabY", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P25", replicate_count=1, analyst="Analyst24", approved_flag="Y", date_tested="2024-05-04T00:00:00.000+0000"),
    # Single record for CMPD022
    Row(study_id="STUDY026", compound_id="CMPD022", dose_mg=10.0, response_pct=80, subject_id="SUBJ047", time_hr=24, cell_line="A375", drug_name="DrugZ", gene_mutation="MUT26", mutation_type="TypeZ", target_protein="PIK3CA", receptor_type="R26", toxicity_level="Low", efficacy_score=90, ic50=1.5, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B26", test_lab="LabZ", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P26", replicate_count=1, analyst="Analyst25", approved_flag="Y", date_tested="2024-05-05T00:00:00.000+0000"),
    # Compound with only null ic50 values
    Row(study_id="STUDY027", compound_id="CMPD015", dose_mg=10.0, response_pct=80, subject_id="SUBJ048", time_hr=24, cell_line="A375", drug_name="DrugAA", gene_mutation="MUT27", mutation_type="TypeAA", target_protein="PIK3CA", receptor_type="R27", toxicity_level="Low", efficacy_score=90, ic50=None, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B27", test_lab="LabAA", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P27", replicate_count=1, analyst="Analyst26", approved_flag="Y", date_tested="2024-05-06T00:00:00.000+0000"),
    Row(study_id="STUDY027", compound_id="CMPD015", dose_mg=10.0, response_pct=80, subject_id="SUBJ049", time_hr=24, cell_line="A375", drug_name="DrugAA", gene_mutation="MUT27", mutation_type="TypeAA", target_protein="PIK3CA", receptor_type="R27", toxicity_level="Low", efficacy_score=90, ic50=None, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B27", test_lab="LabAA", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P27", replicate_count=1, analyst="Analyst26", approved_flag="Y", date_tested="2024-05-07T00:00:00.000+0000"),
    Row(study_id="STUDY027", compound_id="CMPD015", dose_mg=10.0, response_pct=80, subject_id="SUBJ050", time_hr=24, cell_line="A375", drug_name="DrugAA", gene_mutation="MUT27", mutation_type="TypeAA", target_protein="PIK3CA", receptor_type="R27", toxicity_level="Low", efficacy_score=90, ic50=None, auc=120, therapeutic_area="Oncology", organism="Human", tissue_type="Skin", test_batch="B27", test_lab="LabAA", temperature_c=37, ph_level=7.4, solvent="DMSO", plate_id="P27", replicate_count=1, analyst="Analyst26", approved_flag="Y", date_tested="2024-05-08T00:00:00.000+0000"),
]

# Create DataFrame
df_dosage_response = spark.createDataFrame(test_data, schema=dosage_response_schema)

# Write to Unity Catalog table (overwrite for test)
df_dosage_response.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("purgo_playground.dosage_response_analysis")
